import { Component, OnInit } from '@angular/core';
import { NgForm } from '@angular/forms';
import { ActivatedRoute, ParamMap } from '@angular/router';
import { LeadService } from '../lead/lead.service';
import { Post } from '../lead/lead.module';
import * as html2pdf from 'html2pdf.js';
import * as jsPDF from 'jspdf';
import { Router } from '@angular/router';
import { Title } from '@angular/platform-browser';

@Component({
  selector: 'app-pdf-page',
  templateUrl: './itinerary.component.html',
  styleUrls: ['./itinerary.component.css']
})
export class ItineraryComponent implements OnInit {


  selectedOption = '';
  airfare;
  leadtitle = '';
  customerName = '';
  requirement = '';
  shortNote = '';
  leadStatus = '';
  holidayType = '';
  noOfAdult = '';
  noOfKids = '';
  noOfInfants = '';
  hotelPerformance = '';
  personCouple = '';
  currency = '';
  amount = '';
  destination = '';
  groupTourPackage = '';
  customeremail = '';
  customermobile = '';
  customeraddress = '';
  startdate = '';
  enddate = '';
  hotelCheckIN = '';
  hotelCheckOut = '';
  cabTimeDate = '';
  transportation = '';
  hotelstay = '';
  sightseeing = '';
  visafees = '';
  governmentTax = '';
  surcharge = '';
  cruisestay = '';
  freegoodies = '';
  stayandmeals = '';
  passportfees = '';
  staybreakfast = '';
  tourmanager = '';
  breakfastanddinner = '';
  totaldayscount = '';
  itineraryType = '';
  itineraryName = '';
  citiesCovers = '';
  welcomeOption = '';
  itineraryWelcome = '';
  thankYouOption = '';

  dayPlanOption = '';

  dayTitleDay1Check = '';
  dayPlanDay1Check = '';
  transportTitleDay1Check = '';
  transportModeDay1Check = '';
  transDepartCountryDay1Check = '';
  transArrivalCountryDay1Check = '';
  transDepartCityDay1Check = '';
  transArrivalCityDay1Check = '';
  transStartingPointtDay1Check = '';
  transEndingPointtDay1Check = '';
  transDepartDateDay1Check = '';
  transArrivalDateDay1Check = '';
  transActualDepartureTimeDay1Check = '';
  transReportingTimeDay1Check = '';
  transActualArrivalTimeDay1Check = '';
  transportationNoteDay1Check = '';
  hotelCountryNameDay1Check = '';
  hotelStateNameDay1Check = '';
  hotelCityNameDay1Check = '';
  hotelChoseHotelNameDay1Check = '';
  hotelCheckInDateDay1Check = '';
  hotelCheckInTimeDay1Check = '';
  hotelNoOfNightsDay1Check = '';
  hotelNoOfAdultsDay1Check = '';
  hotelNoOfRoomsDay1Check = '';
  hotelNoOfChildDay1Check = '';
  hotelNoOfExtraBedDay1Check = '';
  hotelRoomTypeDay1Check = '';
  hotelNoteDay1Check = '';
  foodTimeDay1Check = '';
  foodNoteDay1Check = '';
  dayTitleDay2Check = '';
  dayPlanDay2Check = '';
  transportTitleDay2Check = '';
  transportModeDay2Check = '';
  transDepartCountryDay2Check = '';
  transArrivalCountryDay2Check = '';
  transDepartCityDay2Check = '';
  transArrivalCityDay2Check = '';
  transStartingPointtDay2Check = '';
  transEndingPointtDay2Check = '';
  transDepartDateDay2Check = '';
  transArrivalDateDay2Check = '';
  transActualDepartureTimeDay2Check = '';
  transReportingTimeDay2Check = '';
  transActualArrivalTimeDay2Check = '';
  transportationNoteDay2Check = '';
  hotelCountryNameDay2Check = '';
  hotelStateNameDay2Check = '';
  hotelCityNameDay2Check = '';
  hotelChoseHotelNameDay2Check = '';
  hotelCheckInDateDay2Check = '';
  hotelCheckInTimeDay2Check = '';
  hotelNoOfNightsDay2Check = '';
  hotelNoOfAdultsDay2Check = '';
  hotelNoOfRoomsDay2Check = '';
  hotelNoOfChildDay2Check = '';
  hotelNoOfExtraBedDay2Check = '';
  hotelRoomTypeDay2Check = '';
  hotelNoteDay2Check = '';
  foodTimeDay2Check = '';
  foodNoteDay2Check = '';
  dayTitleDay3Check = '';
  dayPlanDay3Check = '';
  transportTitleDay3Check = '';
  transportModeDay3Check = '';
  transDepartCountryDay3Check = '';
  transArrivalCountryDay3Check = '';
  transDepartCityDay3Check = '';
  transArrivalCityDay3Check = '';
  transStartingPointtDay3Check = '';
  transEndingPointtDay3Check = '';
  transDepartDateDay3Check = '';
  transArrivalDateDay3Check = '';
  transActualDepartureTimeDay3Check = '';
  transReportingTimeDay3Check = '';
  transActualArrivalTimeDay3Check = '';
  transportationNoteDay3Check = '';
  hotelCountryNameDay3Check = '';
  hotelStateNameDay3Check = '';
  hotelCityNameDay3Check = '';
  hotelChoseHotelNameDay3Check = '';
  hotelCheckInDateDay3Check = '';
  hotelCheckInTimeDay3Check = '';
  hotelNoOfNightsDay3Check = '';
  hotelNoOfAdultsDay3Check = '';
  hotelNoOfRoomsDay3Check = '';
  hotelNoOfChildDay3Check = '';
  hotelNoOfExtraBedDay3Check = '';
  hotelRoomTypeDay3Check = '';
  hotelNoteDay3Check = '';
  foodTimeDay3Check = '';
  foodNoteDay3Check = '';
  dayTitleDay4Check = '';
  dayPlanDay4Check = '';
  transportTitleDay4Check = '';
  transportModeDay4Check = '';
  transDepartCountryDay4Check = '';
  transArrivalCountryDay4Check = '';
  transDepartCityDay4Check = '';
  transArrivalCityDay4Check = '';
  transStartingPointtDay4Check = '';
  transEndingPointtDay4Check = '';
  transDepartDateDay4Check = '';
  transArrivalDateDay4Check = '';
  transActualDepartureTimeDay4Check = '';
  transReportingTimeDay4Check = '';
  transActualArrivalTimeDay4Check = '';
  transportationNoteDay4Check = '';
  hotelCountryNameDay4Check = '';
  hotelStateNameDay4Check = '';
  hotelCityNameDay4Check = '';
  hotelChoseHotelNameDay4Check = '';
  hotelCheckInDateDay4Check = '';
  hotelCheckInTimeDay4Check = '';
  hotelNoOfNightsDay4Check = '';
  hotelNoOfAdultsDay4Check = '';
  hotelNoOfRoomsDay4Check = '';
  hotelNoOfChildDay4Check = '';
  hotelNoOfExtraBedDay4Check = '';
  hotelRoomTypeDay4Check = '';
  hotelNoteDay4Check = '';
  foodTimeDay4Check = '';
  foodNoteDay4Check = '';
  dayTitleDay5Check = '';
  dayPlanDay5Check = '';
  transportTitleDay5Check = '';
  transportModeDay5Check = '';
  transDepartCountryDay5Check = '';
  transArrivalCountryDay5Check = '';
  transDepartCityDay5Check = '';
  transArrivalCityDay5Check = '';
  transStartingPointtDay5Check = '';
  transEndingPointtDay5Check = '';
  transDepartDateDay5Check = '';
  transArrivalDateDay5Check = '';
  transActualDepartureTimeDay5Check = '';
  transReportingTimeDay5Check = '';
  transActualArrivalTimeDay5Check = '';
  transportationNoteDay5Check = '';
  hotelCountryNameDay5Check = '';
  hotelStateNameDay5Check = '';
  hotelCityNameDay5Check = '';
  hotelChoseHotelNameDay5Check = '';
  hotelCheckInDateDay5Check = '';
  hotelCheckInTimeDay5Check = '';
  hotelNoOfNightsDay5Check = '';
  hotelNoOfAdultsDay5Check = '';
  hotelNoOfRoomsDay5Check = '';
  hotelNoOfChildDay5Check = '';
  hotelNoOfExtraBedDay5Check = '';
  hotelRoomTypeDay5Check = '';
  hotelNoteDay5Check = '';
  foodTimeDay5Check = '';
  foodNoteDay5Check = '';
  visaCountry = '';
  visaNoOfDays = '';
  visaType = '';
  visaRequiredDocuments = '';
  inclusionnoteText = '';
  exclusionnoteText = '';
  itineryCostText = '';
  itinerytermsText = '';
  itineryCancelText = '';
  itinerytipsText = '';
  itineryVisaInfoText = '';
  sightseeingSearchCheck = '';
  sightseeingSearchdDay2Check = '';
  sightseeingSearchdDay3Check = '';
  sightseeingSearchdDay4Check = '';
  sightseeingSearchdDay5Check = '';
  sightseeingSearchdDay6Check = '';
  sightseeingSearchdDay7Check = '';
  sightseeingSearchdDay8Check = '';
  sightseeingSearchdDay9Check = '';
  sightseeingSearchdDay10Check = '';
  sightseeingSearchdDay11Check = '';
  sightseeingSearchdDay12Check = '';
  sightseeingSearchdDay13Check = '';
  sightseeingSearchdDay14Check = '';
  sightseeingSearchdDay15Check = '';
  sightseeingSearchdDay16Check = '';
  sightseeingSearchdDay17Check = '';
  sightseeingSearchdDay18Check = '';
  sightseeingSearchdDay19Check = '';
  sightseeingSearchdDay20Check = '';



  post: Post;
  isLoading = false;
  successalert = false;
  // tslint:disable-next-line: max-line-length
  vehicleType = ['Airplane', 'Auto', 'Boat', 'Bus', 'Bus (12 Seater)', 'Car (Indica or Equivalent 4 Seater)',
  'Car (Innova or Equivalent 6 Seater)', 'Suv (Big Car)', 'Tempo Traveller (26 Seater)', 'Tempo Traveller (9 Seater)', 'Train',
  'Tempo Traveller (22 Seater)', 'Tempo Traveller (14 Seater)', 'Tempo Traveller (17 Seater)', 'Tempo Traveller (19 Seater)',
  'Tuk Tuk',  'Water Crafts', 'Walk', 'Van'];

  private mode = 'create';
  private postId = null;


  constructor(public postsService: LeadService, public route: ActivatedRoute, private router: Router, private titleService: Title) {
  }

  onSaveLead(form: NgForm) {
    form.value.userId = sessionStorage.getItem('USERID');
    form.value.email = sessionStorage.getItem('EMAIL');
    if (form.invalid) {
      return;
    }
    this.isLoading = true;
    if (this.mode === 'create') {
      // tslint:disable-next-line: max-line-length
      this.postsService.addPost(form.value);
    } else {
      this.isLoading = false;
      form.value.id = this.postId;
      this.postsService.updatePost(this.postId, form.value);
    }
    form.resetForm();
    this.successalert = true;
    setTimeout(() => { this.successalert = false; }, 1000);
  }

  ngOnInit() {
    this.route.paramMap.subscribe((paramMap: ParamMap) => {
      if (paramMap.has('postId')) {
        this.mode = 'edit';
        this.postId = paramMap.get('postId');
        this.isLoading = true;
        this.post = this.postsService.getPost(this.postId);
        this.isLoading = false;
        this.selectedOption = this.post.requirement;
        this.welcomeOption = this.post.itineraryWelcome;
        this.thankYouOption = this.post.itinerarythankyou;
        this.dayPlanOption = this.post.itineraryDayPlans;
        this.dayTitleDay1Check = this.post.dayTitleDay1;
        this.dayPlanDay1Check = this.post.dayPlanDay1;
        this.transportTitleDay1Check = this.post.transportTitleDay1;
        this.transportModeDay1Check = this.post.transportModeDay1;
        this.transDepartCountryDay1Check = this.post.transDepartCountryDay1;
        this.transArrivalCountryDay1Check = this.post.transArrivalCountryDay1;
        this.transDepartCityDay1Check = this.post.transDepartCityDay1;
        this.transArrivalCityDay1Check = this.post.transArrivalCityDay1;
        this.transArrivalCityDay1Check = this.post.transArrivalCityDay1;
        this.transEndingPointtDay1Check = this.post.transEndingPointtDay1;
        this.transDepartDateDay1Check = this.post.transDepartDateDay1;
        this.transArrivalDateDay1Check = this.post.transArrivalDateDay1;
        this.transActualDepartureTimeDay1Check = this.post.transActualDepartureTimeDay1;
        this.transReportingTimeDay1Check = this.post.transReportingTimeDay1;
        this.transActualArrivalTimeDay1Check = this.post.transActualArrivalTimeDay1;
        this.transportationNoteDay1Check = this.post.transportationNoteDay1;
        this.hotelCountryNameDay1Check = this.post.hotelCountryNameDay1;
        this.hotelCityNameDay1Check = this.post.hotelCityNameDay1;
        this.hotelChoseHotelNameDay1Check = this.post.hotelChoseHotelNameDay1;
        this.hotelCheckInDateDay1Check = this.post.hotelCheckInDateDay1;
        this.hotelCheckInTimeDay1Check = this.post.hotelCheckInTimeDay1;
        this.hotelNoOfNightsDay1Check = this.post.hotelNoOfNightsDay1;
        this.hotelNoOfAdultsDay1Check = this.post.hotelNoOfAdultsDay1;
        this.hotelNoOfRoomsDay1Check = this.post.hotelNoOfRoomsDay1;
        this.hotelNoOfChildDay1Check = this.post.hotelNoOfChildDay1;
        this.hotelNoOfExtraBedDay1Check = this.post.hotelNoOfExtraBedDay1;
        this.hotelRoomTypeDay1Check = this.post.hotelRoomTypeDay1;
        this.hotelNoteDay1Check = this.post.hotelNoteDay1;
        this.foodTimeDay1Check = this.post.foodTimeDay1;
        this.foodNoteDay1Check = this.post.foodNoteDay1;
        this.hotelStateNameDay1Check = this.post.hotelStateNameDay1;
        this.dayTitleDay2Check = this.post.dayTitleDay2;
        this.dayPlanDay2Check = this.post.dayPlanDay2;
        this.transportTitleDay2Check = this.post.transportTitleDay2;
        this.transportModeDay2Check = this.post.transportModeDay2;
        this.transDepartCountryDay2Check = this.post.transDepartCountryDay2;
        this.transArrivalCountryDay2Check = this.post.transArrivalCountryDay2;
        this.transDepartCityDay2Check = this.post.transDepartCityDay2;
        this.transArrivalCityDay2Check = this.post.transArrivalCityDay2;
        this.transStartingPointtDay2Check = this.post.transStartingPointtDay2;
        this.transEndingPointtDay2Check = this.post.transEndingPointtDay2;
        this.transDepartDateDay2Check = this.post.transDepartDateDay2;
        this.transArrivalDateDay2Check = this.post.transArrivalDateDay2;
        this.transActualDepartureTimeDay2Check = this.post.transActualDepartureTimeDay2;
        this.transReportingTimeDay2Check = this.post.transReportingTimeDay2;
        this.transActualArrivalTimeDay2Check = this.post.transActualArrivalTimeDay2;
        this.transportationNoteDay2Check = this.post.transportationNoteDay2;
        this.hotelCountryNameDay2Check = this.post.hotelCountryNameDay2;
        this.hotelCityNameDay2Check = this.post.hotelCityNameDay2;
        this.hotelChoseHotelNameDay2Check = this.post.hotelChoseHotelNameDay2;
        this.hotelCheckInDateDay2Check = this.post.hotelCheckInDateDay2;
        this.hotelCheckInTimeDay2Check = this.post.hotelCheckInTimeDay2;
        this.hotelNoOfNightsDay2Check = this.post.hotelNoOfNightsDay2;
        this.hotelNoOfAdultsDay2Check = this.post.hotelNoOfAdultsDay2;
        this.hotelNoOfRoomsDay2Check = this.post.hotelNoOfRoomsDay2;
        this.hotelNoOfChildDay2Check = this.post.hotelNoOfChildDay2;
        this.hotelNoOfExtraBedDay2Check = this.post.hotelNoOfExtraBedDay2;
        this.hotelRoomTypeDay2Check = this.post.hotelRoomTypeDay2;
        this.hotelNoteDay2Check = this.post.hotelNoteDay2;
        this.foodTimeDay2Check = this.post.foodTimeDay2;
        this.foodNoteDay2Check = this.post.foodNoteDay2;
        this.hotelStateNameDay2Check = this.post.hotelStateNameDay2;
        this.dayTitleDay3Check = this.post.dayTitleDay3;
        this.dayPlanDay3Check = this.post.dayPlanDay3;
        this.transportTitleDay3Check = this.post.transportTitleDay3;
        this.transportModeDay3Check = this.post.transportModeDay3;
        this.transDepartCountryDay3Check = this.post.transDepartCountryDay3;
        this.transArrivalCountryDay3Check = this.post.transArrivalCountryDay3;
        this.transDepartCityDay3Check = this.post.transDepartCityDay3;
        this.transArrivalCityDay3Check = this.post.transArrivalCityDay3;
        this.transArrivalCityDay3Check = this.post.transArrivalCityDay3;
        this.transEndingPointtDay3Check = this.post.transEndingPointtDay3;
        this.transDepartDateDay3Check = this.post.transDepartDateDay3;
        this.transArrivalDateDay3Check = this.post.transArrivalDateDay3;
        this.transActualDepartureTimeDay3Check = this.post.transActualDepartureTimeDay3;
        this.transReportingTimeDay3Check = this.post.transReportingTimeDay3;
        this.transActualArrivalTimeDay3Check = this.post.transActualArrivalTimeDay3;
        this.transportationNoteDay3Check = this.post.transportationNoteDay3;
        this.hotelCountryNameDay3Check = this.post.hotelCountryNameDay3;
        this.hotelCityNameDay3Check = this.post.hotelCityNameDay3;
        this.hotelChoseHotelNameDay3Check = this.post.hotelChoseHotelNameDay3;
        this.hotelCheckInDateDay3Check = this.post.hotelCheckInDateDay3;
        this.hotelCheckInTimeDay3Check = this.post.hotelCheckInTimeDay3;
        this.hotelNoOfNightsDay3Check = this.post.hotelNoOfNightsDay3;
        this.hotelNoOfAdultsDay3Check = this.post.hotelNoOfAdultsDay3;
        this.hotelNoOfRoomsDay3Check = this.post.hotelNoOfRoomsDay3;
        this.hotelNoOfChildDay3Check = this.post.hotelNoOfChildDay3;
        this.hotelNoOfExtraBedDay3Check = this.post.hotelNoOfExtraBedDay3;
        this.hotelRoomTypeDay3Check = this.post.hotelRoomTypeDay3;
        this.hotelNoteDay3Check = this.post.hotelNoteDay3;
        this.foodTimeDay3Check = this.post.foodTimeDay3;
        this.foodNoteDay3Check = this.post.foodNoteDay3;
        this.hotelStateNameDay3Check = this.post.hotelStateNameDay3;
        this.dayTitleDay4Check = this.post.dayTitleDay4;
        this.dayPlanDay4Check = this.post.dayPlanDay4;
        this.transportTitleDay4Check = this.post.transportTitleDay4;
        this.transportModeDay4Check = this.post.transportModeDay4;
        this.transDepartCountryDay4Check = this.post.transDepartCountryDay4;
        this.transArrivalCountryDay4Check = this.post.transArrivalCountryDay4;
        this.transDepartCityDay4Check = this.post.transDepartCityDay4;
        this.transArrivalCityDay4Check = this.post.transArrivalCityDay4;
        this.transArrivalCityDay4Check = this.post.transArrivalCityDay4;
        this.transEndingPointtDay4Check = this.post.transEndingPointtDay4;
        this.transDepartDateDay4Check = this.post.transDepartDateDay4;
        this.transArrivalDateDay4Check = this.post.transArrivalDateDay4;
        this.transActualDepartureTimeDay4Check = this.post.transActualDepartureTimeDay4;
        this.transReportingTimeDay4Check = this.post.transReportingTimeDay4;
        this.transActualArrivalTimeDay4Check = this.post.transActualArrivalTimeDay4;
        this.transportationNoteDay4Check = this.post.transportationNoteDay4;
        this.hotelCountryNameDay4Check = this.post.hotelCountryNameDay4;
        this.hotelCityNameDay4Check = this.post.hotelCityNameDay4;
        this.hotelChoseHotelNameDay4Check = this.post.hotelChoseHotelNameDay4;
        this.hotelCheckInDateDay4Check = this.post.hotelCheckInDateDay4;
        this.hotelCheckInTimeDay4Check = this.post.hotelCheckInTimeDay4;
        this.hotelNoOfNightsDay4Check = this.post.hotelNoOfNightsDay4;
        this.hotelNoOfAdultsDay4Check = this.post.hotelNoOfAdultsDay4;
        this.hotelNoOfRoomsDay4Check = this.post.hotelNoOfRoomsDay4;
        this.hotelNoOfChildDay4Check = this.post.hotelNoOfChildDay4;
        this.hotelNoOfExtraBedDay4Check = this.post.hotelNoOfExtraBedDay4;
        this.hotelRoomTypeDay4Check = this.post.hotelRoomTypeDay4;
        this.hotelNoteDay4Check = this.post.hotelNoteDay4;
        this.foodTimeDay4Check = this.post.foodTimeDay4;
        this.foodNoteDay4Check = this.post.foodNoteDay4;
        this.hotelStateNameDay4Check = this.post.hotelStateNameDay4;
        this.dayTitleDay5Check = this.post.dayTitleDay5;
        this.dayPlanDay5Check = this.post.dayPlanDay5;
        this.transportTitleDay5Check = this.post.transportTitleDay5;
        this.transportModeDay5Check = this.post.transportModeDay5;
        this.transDepartCountryDay5Check = this.post.transDepartCountryDay5;
        this.transArrivalCountryDay5Check = this.post.transArrivalCountryDay5;
        this.transDepartCityDay5Check = this.post.transDepartCityDay5;
        this.transArrivalCityDay5Check = this.post.transArrivalCityDay5;
        this.transArrivalCityDay5Check = this.post.transArrivalCityDay5;
        this.transEndingPointtDay5Check = this.post.transEndingPointtDay5;
        this.transDepartDateDay5Check = this.post.transDepartDateDay5;
        this.transArrivalDateDay5Check = this.post.transArrivalDateDay5;
        this.transActualDepartureTimeDay5Check = this.post.transActualDepartureTimeDay5;
        this.transReportingTimeDay5Check = this.post.transReportingTimeDay5;
        this.transActualArrivalTimeDay5Check = this.post.transActualArrivalTimeDay5;
        this.transportationNoteDay5Check = this.post.transportationNoteDay5;
        this.hotelCountryNameDay5Check = this.post.hotelCountryNameDay5;
        this.hotelCityNameDay5Check = this.post.hotelCityNameDay5;
        this.hotelChoseHotelNameDay5Check = this.post.hotelChoseHotelNameDay5;
        this.hotelCheckInDateDay5Check = this.post.hotelCheckInDateDay5;
        this.hotelCheckInTimeDay5Check = this.post.hotelCheckInTimeDay5;
        this.hotelNoOfNightsDay5Check = this.post.hotelNoOfNightsDay5;
        this.hotelNoOfAdultsDay5Check = this.post.hotelNoOfAdultsDay5;
        this.hotelNoOfRoomsDay5Check = this.post.hotelNoOfRoomsDay5;
        this.hotelNoOfChildDay5Check = this.post.hotelNoOfChildDay5;
        this.hotelNoOfExtraBedDay5Check = this.post.hotelNoOfExtraBedDay5;
        this.hotelRoomTypeDay5Check = this.post.hotelRoomTypeDay5;
        this.hotelNoteDay5Check = this.post.hotelNoteDay5;
        this.foodTimeDay5Check = this.post.foodTimeDay5;
        this.foodNoteDay5Check = this.post.foodNoteDay5;
        this.hotelStateNameDay5Check = this.post.hotelStateNameDay5;
        this.visaCountry = this.post.visaCountry;
        this.visaNoOfDays = this.post.visaNoOfDays;
        this.visaType = this.post.visaType;
        this.visaRequiredDocuments = this.post.visaRequiredDocuments;
        this.inclusionnoteText = this.post.inclusionnote;
        this.exclusionnoteText = this.post.exclusionnote;
        this.itineryCostText = this.post.itineryCost;
        this.itinerytermsText = this.post.itineryterms;
        this.itineryCancelText = this.post.itineryCancel;
        this.itinerytipsText = this.post.itinerytips;
        this.itineryVisaInfoText = this.post.itineryVisaInfo;
        this.sightseeingSearchCheck = this.post.sightseeingSearch;
        this.sightseeingSearchdDay2Check = this.post.sightseeingSearchdDay2;
        this.sightseeingSearchdDay3Check = this.post.sightseeingSearchdDay3;
        this.sightseeingSearchdDay4Check = this.post.sightseeingSearchdDay4;
        this.sightseeingSearchdDay5Check = this.post.sightseeingSearchdDay5;
        this.sightseeingSearchdDay6Check = this.post.sightseeingSearchdDay6;
        this.sightseeingSearchdDay7Check = this.post.sightseeingSearchdDay7;
        this.sightseeingSearchdDay8Check = this.post.sightseeingSearchdDay8;
        this.sightseeingSearchdDay9Check = this.post.sightseeingSearchdDay9;
        this.sightseeingSearchdDay10Check = this.post.sightseeingSearchdDay10;
        this.sightseeingSearchdDay11Check = this.post.sightseeingSearchdDay11;
        this.sightseeingSearchdDay12Check = this.post.sightseeingSearchdDay12;
        this.sightseeingSearchdDay13Check = this.post.sightseeingSearchdDay13;
        this.sightseeingSearchdDay14Check = this.post.sightseeingSearchdDay14;
        this.sightseeingSearchdDay15Check = this.post.sightseeingSearchdDay15;
        this.sightseeingSearchdDay16Check = this.post.sightseeingSearchdDay16;
        this.sightseeingSearchdDay17Check = this.post.sightseeingSearchdDay17;
        this.sightseeingSearchdDay18Check = this.post.sightseeingSearchdDay18;
        this.sightseeingSearchdDay19Check = this.post.sightseeingSearchdDay19;
        this.sightseeingSearchdDay20Check = this.post.sightseeingSearchdDay20;
      } else {
        this.mode = 'create';
        this.postId = null;
      }
    });
  }

  downloadPDF() {
    this.titleService.setTitle(this.post.itineraryCustomer + '_' + this.post.itineraryTitle + '_' + this.post.itineraryNights);
    window.print();
    this.titleService.setTitle(this.post.itineraryCustomer + '_' + this.post.itineraryTitle + '_' + this.post.itineraryNights);
    this.router.navigate(['viewlead']);
    this.titleService.setTitle('Angular App');
  }
}
